apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: app
spec:
  project: helm-test1

  source:
    repoURL: https://github.com/GitHubforGitLab/test.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
