apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccountName: example-serviceaccount
      containers:
      - name: test
        image: ubuntu:latest
        command: ["sh", "-c", "cat /var/run/secrets/kubernetes.io/serviceaccount/token && cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt && sleep infinity"]