apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: lsj
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccountName: example-serviceaccount
    spec:
      containers:
      - name: test
        image: ubuntu:latest
