apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  serviceAccountName: example-serviceaccount
  containers:
  - name: test
    image: ubuntu:latest
    command: ["sh", "-c", "sleep infinity"]
  volumes:
  - name: all-in-one
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 600
          path: token